-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 27, 2021 at 04:02 PM
-- Server version: 10.4.13-MariaDB
-- PHP Version: 7.4.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pd_uspon`
--

-- --------------------------------------------------------

--
-- Table structure for table `guides`
--

CREATE TABLE `guides` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `photo` varchar(255) NOT NULL,
  `bio` text NOT NULL,
  `city` varchar(255) NOT NULL,
  `number` int(255) NOT NULL,
  `mail` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `guides`
--

INSERT INTO `guides` (`id`, `name`, `slug`, `photo`, `bio`, `city`, `number`, `mail`) VALUES
(1, 'Srđan Marković', 'srdjan_markovic', 'srdjan_markovic.jpg', 'Aenean et sodales mauris, eu feugiat lorem. Praesent eget semper lectus, eget laoreet tortor.<br><br>\r\n\r\nAliquam vestibulum orci ullamcorper justo pretium, ut cursus dui bibendum. In eleifend orci ut dolor ultrices pharetra. Ut laoreet quis mi eu imperdiet. Donec convallis eleifend efficitur. Nam varius lorem sed augue auctor mollis. Nam volutpat elementum lacinia. Cras fermentum leo pulvinar sapien auctor vestibulum. Cras vitae rutrum turpis.<br><br>\r\n<b>\r\nUt laoreet quis mi eu imperdiet. Aliquam vestibulum orci ullamcorper justo pretium, ut cursus dui bibendum. In eleifend orci ut dolor ultrices pharetra.</b>', 'Beograd', 64559598, 'srdjanm@uspon.rs'),
(2, 'Svetlana Rubov', 'svetlana_rubov', 'svetlana_rubov.jpg', ' Quisque quis magna nisi. Donec finibus felis at diam malesuada volutpat. Integer accumsan ante in iaculis pharetra. Praesent eget molestie ligula, id lobortis nisi. Morbi eget urna convallis, venenatis ex id, pharetra risus. Nullam ut nibh vel enim suscipit interdum. Duis eget magna purus.<br><br>\r\n\r\nNullam sagittis urna leo, non vehicula odio feugiat eu. Praesent ipsum dolor, lacinia vitae eros in, iaculis sollicitudin nisi. Nulla facilisi.<br><br>\r\n<b> Proin bibendum, nisi eget consectetur dignissim, arcu tellus convallis magna, at molestie mi lorem eget ipsum.</b>', 'Beograd', 65998565, 'svetlanar@uspon.rs'),
(3, 'Miloš Petrović', 'milos_petrovic', 'milos_petrovic.jpg', ' In auctor eu mauris id aliquet. Suspendisse potenti. Duis quis orci in enim maximus tristique vel a turpis. Sed semper ante lectus, eget imperdiet libero facilisis ut. In facilisis, enim in dapibus placerat, purus ex tempus quam, pretium ultricies nisl dui consectetur nisl. In a finibus purus. Integer in venenatis odio, ac dapibus enim. Maecenas lobortis, ligula tristique eleifend porta, felis enim congue libero, non porta neque metus a velit. Curabitur euismod luctus orci, et pulvinar urna dignissim ut.\r\n<br><br>\r\n<b>\r\nProin eget semper mauris. Phasellus ac vehicula nisl, sit amet auctor magna. Maecenas consequat ex quam, nec aliquet risus tincidunt ut. Nullam euismod odio nunc, eu luctus libero pretium lobortis. Morbi tristique purus ac nisi malesuada, vitae lobortis velit congue.</b>', 'Niš', 63889982, 'milosp@uspon.rs'),
(4, 'Tamara Crnomarković', 'tamara_crnomarkovic', 'tamara_crnomarkovic.jpg', ' Suspendisse leo ipsum, ornare quis ornare in, sollicitudin et leo. Curabitur placerat sodales tristique. Morbi varius imperdiet risus sit amet vestibulum. Donec pretium nulla diam, eu suscipit libero malesuada eu. Quisque maximus augue non elit luctus euismod. Aenean ut neque ut nulla mattis scelerisque. In consequat finibus erat eu malesuada. Vivamus eu lacinia nisl. Pellentesque gravida augue nec neque mollis porta. Fusce sollicitudin interdum facilisis.\r\n<br><br>\r\nIn auctor eu mauris id aliquet. Suspendisse potenti. Duis quis orci in enim maximus tristique vel a turpis.\r\n<br><br>\r\n<b> Sed semper ante lectus, eget imperdiet libero facilisis ut. In facilisis, enim in dapibus placerat, purus ex tempus quam, pretium ultricies nisl dui consectetur nisl.</b>', 'Zaječar', 64223585, 'tamarac@uspon.rs'),
(5, 'Dragan Aleksić', 'dragan_aleksic', 'dragan_aleksic.jpg', 'Proin eget semper mauris. Phasellus ac vehicula nisl, sit amet auctor magna. Maecenas consequat ex quam, nec aliquet risus tincidunt ut. Nullam euismod odio nunc, eu luctus libero pretium lobortis. Morbi tristique purus ac nisi malesuada, vitae lobortis velit congue. Proin cursus, nibh vitae cursus commodo, massa lectus sodales nisi, ut tristique velit odio vel dolor. Nulla in aliquam est.\r\n<br><br>\r\n<b> Donec ullamcorper orci vel convallis laoreet. In faucibus blandit dolor id posuere. Vestibulum orci elit, sodales vitae ante ut, aliquam varius risus. Suspendisse potenti. </b>\r\n<br><br>\r\nVestibulum aliquam molestie lectus sed vestibulum. Aliquam ac eros ipsum. Maecenas rutrum purus eu magna iaculis blandit. ', 'Zaječar', 65939622, 'dragana@uspon.rs');

-- --------------------------------------------------------

--
-- Table structure for table `travels`
--

CREATE TABLE `travels` (
  `id` int(11) NOT NULL,
  `heading` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `difficulty` int(11) NOT NULL,
  `travel_image` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `guide_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `travels`
--

INSERT INTO `travels` (`id`, `heading`, `body`, `difficulty`, `travel_image`, `date`, `guide_id`) VALUES
(1, 'Fruska Gora, Zmajevac (430m)', 'Komunalne službe ne odlaze u prirodu, molimo vas da vaše smeće ponesete sa sobom. Čuvamo i volimo našu zemlju! Saznaj više.\r\n<br><br>\r\nNa najvišim delovima Fruške gore nalaze se mnogobrojna izletišta koja s prvim danima proleća pa sve do početka hladnijih jesenjih dana postaju odredišta mnogih zaljubljenika u prirodu. Jedno od tih je i izletište Zmajevac, sa kog se pruža jedan od najlepših pogleda na Srem, posebno u večernjim satima kada počinju da se pale ulične svetiljke u obližnjim mestima. Ovo izletište je opremljeno mnogobrojnim drvenim klupama i stolovima, od kojih su neki natkriveni kao pravi letnjikovci i potpuno usklađeni s okruženjem. Postoje i ozidana ložišta koja olakšavaju pripremu roštilja.\r\n<br><br>\r\nZmajevac se nalazi na raskršću Partizanskog puta i puta Vrdnik–Rakovac. Nedaleko su i Iriški venac i Ledinačko jezero do kojih se može stići šumskim putem.', 1, '', '2021-01-03', 2),
(2, 'Bukulja (696m)', 'Planina Bukulja, nova zvezda domaće serije Kalkanski krugovi, sve više privlači izletnike, a posebno turiste koji žude za novim otkrićima. Kako nas je pandemija usmerila na istraživanje Srbije, veliki broj turista u želji za prirodom i aktivnim odmorom svoj dnevni odmor provodi na lepotici Šumadije, planini Bukulja.\r\n <br><br>\r\nNa Bukulji se nalaze objekti izgrađeni krajem 20. veka i uglavnom su to vikendice. Od prošle godine nekoliko vikendica je kategorisano i rade sa turistima. Takođe, na vrhu planine krajem 2020. otvoren je rekonstruisan i dograđen Planinarski dom i sada nosi naziv Restoran Bukulja. Iz Turističke organizacije Opštine Aranđelovac navode da im je želja da se ova planina u turističkoj ponudi istakne zaštitom prirode.\r\n \r\nU planu: nacionalni park Bukulja \r\n- Planina Bukulja nije lokacija za izgradnju velikih kompleksa i za sada naša želja je da se u turističkoj ponudi istaknemo time što smo uspeli da zaštitimo narušavanje prirodnog ambijenta. Udaljenost centra Aranđelovca od vrha planine Bukulje je samo 15 minuta vožnje, a sreću imamo i u tome što saobraćaj na samoj planini nije tranzitni, pa se na nju dovoze isključivo izletnici. Naša želja je da se i u budućnosti planina Bukulja zaštiti kao nacionalni park i time zaustave sve neplanske radnje koje proističu posle ekspanzije određene turističke destinacije - ističu iz Turističke organizacije.\r\n <br><br>\r\nBukulja poseduje obeležene pešačke staze - staze zdravlja, izvore vode, par kategorisanih apartmana, dva jezera na kojima je zabranjeno kupanje jer se Aranđelovac snadbeva pijaćom vodom sa njih, međutim, izlet i fotografisanje su dozvoljeni. Uz usluge Konjičkog kluba, lepote Bukulje možete upoznati kroz jahanje.\r\n <br><br>\r\nNa vrhu se nalaze kafić i restoran, kao i osmatračnica visoka 19 metara sa koje se pruža pogled na čitavu Šumadiju.', 1, '', '2021-01-05', 1),
(3, 'Kosmaj - Beli Kamen (546m), Košutica (463m), manastir Pavlovac, Kasteljan i Tresije', 'Posle Avale, Kosmaj je druga planina najbliža Beogradu. Udaljen je 60 km od glavnog grada. Ova tura je, zapravo, staza Gorštaka, akcija koja se izvodi jednom godišnje i okuplja veliki broj planinarskih klubova iz Srbije.\r\n<br><br>\r\nPočetak ove kružne staze je kod manastira Pavlovac, u selu Koraćica. Do manastira se dolazi autoputem Beograd-Niš, sa koga se isključujete kod skretanja za Mladenovac i Aranđelovac. Kada stignete u Mladenovac, pratite putokaze do manastira.\r\n<br><br>\r\nManastir Pavlovac osnovao je despot Stefan Lazarević, 1425. godine. Posvećen je Svetom Nikoli. Malo iznad manastira kreće markirana planinarska staza. Ali, tu kreću i prvi problemi.\r\n<br><br>\r\nNakon čitavih 200 m, dolazi se do jedne zelene kapije. Zaobiđite je sa leve strane. Ovde lupam prvi minus onome ko je obeležavao stazu.', 1, '', '2021-02-02', 3),
(4, 'Subotička peščara, jezero Tresetište', 'Ovo područje ima karakter šumo-stepe, sa šumskim kompleksima, većinom antropogenog porekla. Prirodna vrednost je uslovljena karakterom i mozaičnošću staništa, među kojima peščarska, stepska i močvarna, daju osnovni pečat predelu sa visokim stepenom biodiverziteta. Najznačajnija su vlažna staništa formirana na podlozi nizijskog treseta u dolini rečice Kireš, koja se smatraju najređim i najugrožnijim staništima u Evropi i svetu.\r\n<br><br>\r\nMeđu očuvanim prirodnim retkostima, mora se pomenuti reliktna šumo-stepska biljka – šafranjika, koja je sinonim za floru Subotičke peščare, s obzirom da je tu njeno jedino nalazište u Vojvodini i Srbiji. Ukupan broj zabeleženih vrsta ptica na području iznosi čak 170 vrsta, što je rezultat velike raznovrsnosti staništa.\r\n<br><br>\r\nZabeleženo je prisustvo retke vrste glodara – vojvođanskog slepog kučeta, koja svoj život provodi pod zemljom, u sistemu hodnika, u potrazi za hranom – korenjem trava, rizomima i lukovicama. Ova vrsta je još pre samo sto godina bila široko rasprostranjena u Vojvodini, ali pretvaranjem izvornih stepa u njive, njen areal se izuzetno smanjio.\r\n<br><br>\r\nPredeo izuzetnih odlika Subotička peščara zaštićen je od 2003. godine i svrstan u II kategoriju zaštite, kao zaštićeno dobro od nacionalnog značaja. Zaštitom je obuhvaćena površina od 5370 hektara + 2773 hektara zaštitne zone.\r\n<br><br>\r\nDelimično su sačuvane izvorne predeone karakteristike, nastale u interakciji čoveka i prirode, a na području i njegovom neposrednom okruženju zadržali su se neki oblici tradicionalnog privređivanja i života, kao i pojedinačni salaši.', 1, '', '2021-02-06', 2),
(5, 'Sokolske planine (973m)', 'Planina Rožanj pripada Sokolskim planinama i nalazi se u blizini varošice Pecke. Od Beograda je udaljena oko 130 km. Najkraći put je Ibarskom magistralom, do Valjeva. U Valjevu se skreće na put za Ljuboviju, koji dalje vodi preko Suvodanja, do Pecke. Od Beograda do Valjeva ima oko 100 km i još 30 km do Pecke, što je oko 2-2,5 sata vožnje. Kada se prođe Pecka, nakon 10-15 minuta vožnje, dolazi se do prevoja Proslop, odakle počinje staza za Rožanj. Pored magistralnog puta, sa desne strane, postoji crvena tabla, sa natpisom “Rožanj“, koja označava početak staze. Staza je dobro markirana, tako da ne postoji mogućnost da se zaluta. ', 1, '', '2021-01-14', 2),
(6, 'Povlen, taorska vrela', 'Taorska vrela su kaskadni slapovi koji se nalaze na padinama planine Povlen u blizini Valjeva. Izviru u selu Donji Taor i predstavljaju spomenik prirode. Na ovim izvorima koji su bili prebogati vodom, nalazilo se čak 12 vodenica sve do 80-ih godina prošlog veka kada se voda iz ovog izvora preusmerila za grad Kosjerić. Na taj način se kapacitet vode smanjio i nažalost, narušena je njihova prirodna lepota. Nekada je izvor vode izbijao iz pećine za koji kažu da se nije mogao opisati rečima sve dok tok vode nije preusmeren. Danas su tu samo dve vodenice, od kojih je jedna obnovljena i radi, a druga je zarasla u mahovinu i prepuštena zubu vremena. ', 1, '', '2021-04-10', 4),
(7, 'Maljen, Divčibare (980 m), Crni vrh (1096 m)', 'Divčibare su poznato turističko mesto koje se nalazi četrdesetak kilometara od grada Valjeva. Divčibare su deo planine Maljen. Zapravo, Divčibare su visoravan koja se nalazi na 980 m.n.v.\r\n<br><br>\r\nOd Beograda do Divčibara ima oko 125 km. Putuje se ibarskom magistralom do skretanja za Valjevo. Sa magistralnog puta koji vodi prema Valjevu, skreće se levo prema Mionici. Odatle se prate putokazi do 20 km udaljenih Divčibara.\r\n<br><br>\r\nUspon do Crnog vrha počinje iz centra Divčibara. Na Crnom vrhu se nalazi i skijaška staza. Postoje neki putokazi od centra do Crnog vrha, ali su prilično nejasni. Najbolje je kolima otići do vile „Vila“, tu se parkirati i krenuti na uspon. Kada dolazite iz pravca Mionice, prođite centar Divčibara i nakon 200 m skrenite levo na asfaltni put, prema „Markovom konaku“ i vili „Vila“. Od vile „Vila“, pešice nastavite asfaltnim drumom još 100 m i onda skrenite desno. Malo pre skretanja, videćete u šumi putokaz ka ski stazi. ', 2, '', '2021-01-09', 4),
(8, 'Homoljske planine (Zman 607 m)', 'Drugi poznati deo pećine su Ponorske dvorane i potrebno da se prođe kroz uzani prolaz pod nazivom Dveri da se dođe do njih. To je pregradni draperijski zid, koji podseća na oltarske dveri. Nekada davno su Arena i Ponorska dvorana bile jedan entitet, ali ih je priroda pregradila draperijskim zidom. Međutim, kao da je mislila na budućnost ove pećini, ona je ostavila taman toliki prolaz da se napravi turistička staza. Na jednom kraju dvorane se nalazi stalagmit Pećinska jelka, koja zaista liči na okamenjenu jelku. Treća dvorana je Andezitska dvorana koja ima kružnu stazu i krasi je snežno beli tavanički nakit.', 1, 'Homoljske-planine.jpg', '2021-04-02', 5),
(9, 'Brdo Gorica, tvrđava Ram', 'Nalazi se između sela Zatonja i Rama na nadmorskoj visini od 282m. Ovo mesto obiluje vrlo interesantnim prirodnim odlikama. Blizina Dunava koji je presekao Karpate i otvorio prostor od Panonske nizije do Mediterana, kao i visina ovog brda uslovili su česte i snažne vetrove koji se često smenjuju, a od kojih su najpoznatiji Košava i Severac poznat i kao Gornjak. Ovakvo strujanje vetrova stvorilo je idealne uslove za neke ekstremne sportove, kao što je paraglajding.\r\n\r\nZaljubljenike u ovaj sport najčešće možemo sresti u proleće i jesen kada su vetrovi najsnažniji. Paraglajderi dolaze sami ili u grupama i medjusobno preporučuju ovo mesto, sa kako kažu „fantastičnim vetrom za njihova krila“.', 1, '', '2021-04-07', 1),
(11, 'Taorska vrela - Taorska Stena (1021m), reka Skrapež', 'Taorska vrela se nalaze na teritoriji grada Valjeva u Donjem Taoru, nedaleko od puta za Makovište. U ovom prirodnom prostoru, nekad je postojalo 12 vodenica, a sada ih je ostalo samo nekoliko. U podnožju krečnjačkog platoa, na jugoistočnom kraju sinklinalne doline, sa severne strane oivičenog vertikalnom liticom visine 5, širine pri dnu 3 m, iz pećinskog otvora izbija vrelo. Na relativno kratkom rastojanju preko nataloženih bigrenih naslaga, stvoreni su brojni slapovi i vodopadi. Vrela se ulivaju u reku Skrapež, kojoj je izvorište ispod planine Povlen.\r\n\r\nDo vrela se može doći iz Valjeva putem koji ide preko Lelića i Mravinjaca.\r\n\r\nPodručje Taorskih vrela je prepoznatljivo po vrelskoj pećini u podnožju krečnjačkog odseka, odakle izvire glavno vrelo, i široj izvorišnoj zoni sa više malih periodskih izvora.[2] Nizvodno od glavnog vrela nataložena je najveća akumulacija bigra u ovom delu Srbije. Ona je ispresecana mnoštvom živopisnih kaskada i slapova, sa ostacima nekadašnjih vodenica, koji se završavaju vodopadom na ušću Vrelskog potoka u Skrapež, visine oko 4,5 m.', 2, '', '2021-01-15', 5),
(12, 'Vršačke Planine - Kula, Đakov vrh (449 m), Lisičija glava (590 m), Gudurički vrh (641 m)', 'Vršačke planine se uzdižu usred Panonske ravnice u jugozapadnom delu Banata. Pružaju se u pravcu istok-zapad, u dužini od 19 kilometara, sa najvećom širinom od 8 kilometara. Površina im je 170 kvadratnih kilometara, od čega je u Srbiji 122, a u Rumuniji 48 kvadratnih kilometara. Gudurički vrh, sa 641 -{m}- nadmorske visine, najviša je tačka ovih planina i cele Vojvodine. Od ostalih vrhova poznati su Lisičija glava (590 metara), Đakov vrh (449m) i Vršačka kula (399m). Severna padina je strma, dok se južna postepeno spušta u pobrđe, gde se nalaze vršački vinogradi. Vršačke planine spadaju, zajedno s Fruškom gorom, u ostrvske planine, jer su nekada bile ostrvo u Panonskom moru. Čine najseverniji izdanak srpsko-makedonske planinske mase, iako se u starijoj literaturi može pronaći pogrešan podatak o njihovoj pripadnosti Karpatima. Sa planina se pruža pogled na Vršac, Vojvodinu i Rumuniju. ', 1, '', '2021-01-17', 2),
(13, 'Vukan, Veliki Vukan (825 m)', 'Divčibare su poznato turističko mesto koje se nalazi četrdesetak kilometara od grada Valjeva. Divčibare su deo planine Maljen. Zapravo, Divčibare su visoravan koja se nalazi na 980 m.n.v.\r\n\r\nOd Beograda do Divčibara ima oko 125 km. Putuje se ibarskom magistralom do skretanja za Valjevo. Sa magistralnog puta koji vodi prema Valjevu, skreće se levo prema Mionici. Odatle se prate putokazi do 20 km udaljenih Divčibara.\r\n\r\nVukan je jedna od Homoljskih planina koja najviše privlači pažnju planinara. Do Vukana se najbrže stiže autoputem Beograd-Niš, sa koga se isključuje ka Svilajncu. Od Svilajnca se, preko Petrovca na Mlavi, dolazi do sela Ždrelo. Od Beograda do Ždrela ima oko 150 km. U Ždrelu se nalazi moderan spa centar, koji se obavezno posećuje nakon silaska s planine. Termalna voda dostiže temperaturu od 40 ºC i neverovatno prija i opušta nakon višesatnog pešačenja.\r\n\r\nOd Ždrela se skreće levo, do najmlađeg manastira braničevske eparhije, Svete Trojice, odakle počinje staza. Staza je dobro markirana, a visinska razlika je oko 625 m.\r\nStaza većim delom vodi kroz šumu, što predstavlja dobru zaštitu u vrućim letnjim mesecima.\r\n\r\nIzmeđu Velikog i Malog Vukana nalazi se jedna jama, čija dubina doseže sve do podnožja planine. Prema predanju, u nju su Vlasi bacali neverne žene i devojke. Postojalo je verovanje da će ženu, ako nije zgrešila, vetar izbaciti nazad! I zaista, ako u jamu bacite sasušenu travu, ona će, zbog jakog strujanja vazduha, biti izbačena iz nje. Interesantna priča. Na kraju, kada se sa Vukana spustite umorni i zadovoljni, neizbežno je opuštanje u termalnoj banji Ždrelo.', 1, '', '2021-01-19', 2),
(14, 'Sokolske planine (973 m)', 'Planina Rožanj pripada Sokolskim planinama i nalazi se u blizini varošice Pecke. Od Beograda je udaljena oko 130 km. Najkraći put je Ibarskom magistralom, do Valjeva. U Valjevu se skreće na put za Ljuboviju, koji dalje vodi preko Suvodanja, do Pecke. Od Beograda do Valjeva ima oko 100 km i još 30 km do Pecke, što je oko 2-2,5 sata vožnje. Kada se prođe Pecka, nakon 10-15 minuta vožnje, dolazi se do prevoja Proslop, odakle počinje staza za Rožanj. Pored magistralnog puta, sa desne strane, postoji crvena tabla, sa natpisom “Rožanj“, koja označava početak staze. Staza je dobro markirana, tako da ne postoji mogućnost da se zaluta. \r\nPut je uglavnom makadamski. Visinska razlika, od početka staze do vrha, je oko 350 m. Na sve strane puca pogled, iako staza delom ide i kroz šumu.', 1, '', '2021-01-21', 1),
(15, 'Les 2 Alpes, Francuska', 'Les 2 Alpes je jedno od najviših francuskih i evropskih skijališta i nalazi se u \"Haute\" Alpima na jugoistoku Francuske. Skijalište se prostire na visini od 1250 do 3568 m/nv i ima oko 220 km uređenih staza. U sklopu skijališta nalazi se i najveći skijaški glečer u Evropi, koji izlazi do impozantnih 3600 m/nv. Pored perfektno uređenih terena i izuzetno dugačkih staza, koje omogućava velika visinska razlika skijališta, ovaj ski centar nudi i idealne uslove za freeride. Samo turističko mesto je na 1650 m/nv i spada među veća skijaška naselja u Francuskoj.\r\n\r\nLes 2 Alpes je poznat i po bogatoj vanpansionskoj ponudi. Ima jako velik broj restorana, barova, disco-clubova, bioskopa, pizzerija itd. Grad povezuju tri linije autobusa koje voze redovno i mogu prevesti turiste do gotovo bilo kog dela mesta.\r\n\r\nNa 2600 m je međustanica velike kabine koja prevozi 15 ljudi do dna glečera (3.200 m). Glečer je prava poslastica. Počinje na 3200 m, gde je izlazna stanica gondole Jardin. Na tom mestu se nalazi veliki restoran sa širokom terasom sa koje se pruža prekrasan pogled (kada to vremenske prilike dozvole). Glečer se proteže sve do 3568 m. Od početka glečera (odmah pored pomenutog restorana) voze dva paralelna sidra, na čijoj izlaznoj Pogled na naselje Les 2 Alpesstanici skijaši mogu da produže dalje i da jednom gotovo ravnom stazom dođu do početka tanjira, koji vozi na sami vrh i najvišu tačku ovog skijališta na 3.568m. Odatle se pruža nezaboravan pogled na Vrh Les Ecrines koji se još više uzdiže u odnosu na mesto dokle dosežu žičare. Staze na samom vrhu su blage, ali zato izrazito kvalitetne sa vrlo suvim snegom kojeg ima u izobilju.', 3, '', '2021-02-10', 5),
(16, 'Kablar (889 m), Ovčar (985 m)', 'Planina Ovčar nalazi se preko puta planine Kablar. Ove dve planine zajedno čine Ovčarsko-kablarsku klisuru. Klisura je poznata i po svojim manastirima, kojih ima deset, pet na levoj i pet na desnoj obali Zapadne Morave. Zato klisuru zovu još i Srpska Sveta Gora. Uspon na vrh Ovčara počinje od jednog od ovih manastira.\r\n\r\nPolazna tačka je Ovčar Banja. Od Beograda je udaljena 160 km, što je oko 2,5 sata vožnje ibarskom magistralom. U Ovčar Banji postoji planinarski dom PSD „Železničar“, gde se može prenoćiti ukoliko se, pored Ovčara, planira uspon i na Kablar. Iznad doma, na stazi koja vodi prema vrhu Kablara, od 2010. godine postoji ferata. Ali, to je već za ljubitelje ekstremnih sportova.\r\n\r\nPrelaskom visećeg mosta ispred planinarskog doma, izlazi se na ibarsku magistralu. Prelazi se magistrala i ide uzbrdo asfaltnim putem, ka manastiru Preobraženje. Na početku asfaltnog puta je putokaz ka manastiru. Tu se nalazi i jedna česma gde se možete snabdeti čistom planinskom vodom. Za 5 minuta dolazi se do manastira Preobraženje, polazne tačke uspona na Ovčar.\r\n\r\nPlanina Kablar nalazi se 15 km od Čačka i 155 km od Beograda. Do nje se dolazi Ibarskom magistralom. Staza kreće iz Ovčar Banje. Tačnije, od planinarskog doma „Železničar“. Postoji mnoštvo markiranih staza, koje vode do vrha. Neke su duže, a neke kraće, zavisi koliko vam se pešači. Mi smo odabrali stazu koja ide pored isposnice Svetog Save i kojom nam je, do vrha, bilo potrebno oko 3 sata hoda.', 1, '', '2021-02-13', 4),
(17, 'Kučajske planine - vrelo Grze, Veliki Koziji Rog (682 m), Javorački vrh (927 m), Mali Javorak (756 m)', 'Javorak je planina koja uopšte ne bi bila poznata da se u njenom podnožju ne nalazi vrelo Grze, sa dva lepa jezera. Grza je, inače, poznato izletište. Javorak pripada masivu Južnog Kučaja. Rastojanje između Beograda i Grze iznosi 173 km i prelazi se za oko 2,5 sata vožnje. Putuje se autoputem Beograd-Niš, gde se kod Paraćina isključuje na put za Zaječar. Od Paraćina do Grze ima oko 17 km, usput se prolazi kroz mesto Izvor. Odmah nakon Izvora je skretanje za Grzu. Od skretanja, pa do planinarskog doma, ima oko 4,5 km. Usput se prolazi pored prvog jezera.\r\n\r\nStaza počinje od planinarskog doma „Đorđe Živković“, koji je u vlasništvu PD Javorak iz Paraćina. Dom je u funkciji i u njemu se može prespavati. Ispred doma nalazi se mapa staza. Dvadesetak metara dalje je početak staze koja vodi ka najvišem vrhu Javorka i ostalim vrhovima.\r\n\r\nStaza je odlično markirana. U početku se ide makadamskim putem, ali staza vrlo brzo ulazi u šumu. Za oko 2,5 sata umerenog hoda, dolazi se do Javoračkog vrha (927 m). Nažalost, vrh je u šumi, tako da ste uskraćeni za pogled. Pola sata pre vrha nalazi se izvor čiste, pijaće, planinske vode.', 1, '', '2021-02-15', 4),
(18, 'Jelica, stazama zdravlja', 'Planina Jelica, nadomak Čačka, dobila je šumsku stazu zdravlja od manastira Ježevica do vrha same planine. Ona je opremljena putokazima za pešake i bicikliste, a iza ovog veoma korisnog i zanimqivog projekta stoje meštanke Ježevice koje su se okupile u Udruženju „Evgenija“, odlučne u nameri da ožive svoje selo iz koga je mnogo ljudi otišlo put urbanih sredina. \r\n\r\n Ježevičanke imaju ideju da predivnu prirodu svoga sela podele sa drugima, pa su se tokom prošle i ove godine intenzivnije bavile aktivnostima koje promovišu sve blagodeti koje je majka priroda podarila Ježevici, ali i okolnim podjeličkim selima – Banjici, Lipnici i Rajcu. Posvećeno su radile na popularizaciji zdravih stilova života, stavljajući u prvi plan stazu zdravlja koja se proteže od manastira Ježevica do vrha Jelice.\r\n\r\nNataša Vujašević, meštanka Ježevice i potpredsednica udruženja “Evgenija”, idejni je tvorac ekološke staze preko planine Jelice, koju su podržale vredne Jeličanke, medju kojima su profesorke, radnice i domaćice… Ona ističe da su lepote planine Jelice još uvek nedovoljno poznate i da bi u narednom periodu trebalo češće govoriti o njima, kako bi se potencijali ovog izuzetnog bisera prirode bolje iskoristili. Sada, kada je pretežni deo staze zdravlja obeležen putokazima, a posebno u situaciji kada nas je pandemija korone uglavnom primorala da potpuno promenimo stil života, idealno mesto za aktivni jednodnevni odmor u prirodi je upravo Ježevica sa svojim ravničarskim, brdsko-planinskim i planinskim krajolikom. ', 1, '', '2021-02-16', 4),
(19, 'Obuka za Via ferrate, Rudnik, Ostrvica (758 m)', 'Ostrvica nalazi se oko 120 km od Beograda. Neki je smatraju jednim od vrhova planine Rudnik, mada ona svojim izgledom i lokacijom predstavlja zasebnu planinu. Vulkanskog je porekla, visine 758 metara i do vrha vode klizave i strme stene. Zahvaljujući sajlama koje su postavljene, uspon do vrha Ostrovice više ne predstavlja problem, već se pretvara u pravi užitak. Na vrhu se nalaze ostaci srednjovekovne tvrđave, podignute u vreme vladavine dinastije Branković, koja je čuvala rudnike na planini Rudnik.\r\n\r\nIz sela Varnica polazimo markiranom stazom do šume,  a zatim kroš šumu 50-tak metara. Na izlasku iz šume kretanja padinom uz uže, drugi deo kretanje uz fiksiranu sajlu, uspon ka grebenu, izlazak na vrh. Povratak istom stazom, odpenjavanje i ponovno spuštanje niz fiksirano uže.\r\n\r\nNakon povratka sa Ostrvice, planiramo pešačenje do Ibarske magistrale.\r\n\r\nOprema: primerena vremenskim uslovima, obavezno obezbediti tehničku opremu za uspon,  pojas, prusik 2 kom, karabinera 2 kom ili ferata set.\r\n\r\nHrana iz ranca.\r\n', 1, '', '2021-02-19', 2),
(20, 'Goč, Gvozdac (800 m)', 'Planina Goč je niža planina u Srbiji, južno od Zapadne Morave iznad Vrnjačke Banje. Nalazi se u sklopu severnokopaoničkih planina i udaljen je 200 km od Beograda i 31 km od Kraljeva.\r\n\r\nPruža se u pravcu istok-zapad oko 10 km. Najviši vrh je Ljukten 1216 m. Najviši deo je sastavljen od kristalatih škriljaca, a sa strane znatnim delom i od serpentina. Na Goču je izvorište mnogih potoka i rečica koje otiču prema Zapadnoj Moravi na severu i Rasini na jugu.\r\n\r\nGoč je pristupačan sa raznih strana, ali dva glavna puta vode prema njemu: od Kraljeva preko Kamenice do vrha Dobre vode i od Vrnjačke Banje do Stanišinaca. Površina Goča obrasla je bukovom i jelovom šumom, a zastupljeni su i gočki crni bor, hrast kitnjak, plemeniti lišćari i četinarske egzote.\r\n\r\nGoč obiluje šumskim jagodama i raznovrsnim lekovitim biljem. Površine Goča daju bogatu medonosnu ispašu za pčele, a na mestu Gvozdac nalazi se veštačko jezero.\r\n\r\nNa Goču se nalazi i Rimsko groblje, mesto gde su sahranjivani Sasi, rudari koji su ovde vadili rudu i topili gvožđe u vreme Nemanjića. ', 1, '', '2021-02-20', 3),
(21, 'Rudničko pobrđe, Straževica (621m)', 'Polazak u 8h sa parkinga ispred zgrade Opštine Novi Beograd.\r\nPo dolasku u selo Dići, posetićemo crkvu Sv.Jovana Krstitelja, tj. ostatke srednjovekovne crkve i groblja u Dićima.\r\nDolazak oko 11h do motela \"Rudnički breg\" na Rudničkom prevoju. Pauza za kafu.\r\nPešačka tura: Rudnički prevoj 520m - brdo Straževica 621m na kome se nalazi livada \"SRPSKI HOLYWOOD\" (natpis je 2007.godine uradio umetnik Ivan Jakovljević iz sela Mutanj) - preko brda Laz 539m - brdo Grčko groblje 529m - vis Koviljača 497m - Žilovića brdo 510m - vis Medved 429m - vis Sprdanjska kosa 464m na kojem se nalazi nova turistička atrakcija Kamen ljubavi - Milevino brdo 481m - selo Svračkovci 359m.\r\nStaza je dužine 10km, sa 200 m uspona i 370 m spusta. Predviđeno vreme za pešačenje je oko 4 sata. Staze su uglavnom poljske i šumske i pogodne za sve kategorije planinara.\r\nU povratku za Beograd svratićemo u restoran na ručak ili osveženje, po želji.\r\nPovratak u Beograd do 21h.\r\n\r\nU cilju prevencije i zaštite od korona virusa, u prevoznom sredstvu i u svim drugim zatvorenim i otvorenim prostorima, poštovaće se sve obaveze i preporuke kriznog štaba koje budu važile na dan putovanja. Obavezno je korišćenje maski tokom prevoza.', 1, '', '2021-02-25', 2),
(22, 'Rumunija - vodopadi Bigar, Karsa, Moceris, jezero Minis', 'Polazak iz Novog Sada u 5:00 (potrebno je doći 15 minuta ranije), polazak prema Vršcu. Po dolasku u Vršac pravimo kratku pauzu gde nam se pridružuje još nekoliko planinara. Nastavak putovanja.\r\nVozimo se preko Bele Crkve ka prelazu Kaluđerovo gde ulazimo u Rumuniju. Nastavljamo put, I za nekih sat vremena dolazimo do vodopada Bigar (Cascada Bigar), za koji mnogi kažu da je najlepši I najneobičniji vodopad Rumunije. Nalazi se na južnim obroncima Anina planine. Oduševiće vas gracioznost sa kojom se planinski potok sliva niz stenu obraslu mahovinom u reku Minis. Ispod stene, koja je u obliku pečurke ili balske haljine neke princeze, nalazi se pećina oko koje voda pravi hučnu zavesu.\r\nPostoji predivna legenda o ovom vodopadu koju ćemo vam ispričati kada budete uživali u pogledu na njega.\r\n\r\nPut nastavljamo dalje, do banje Herkulana u čijoj blizini ćemo I biti smešteni. Ko želi može da ide u organizovani obilazak vodopada Vanturatoarea (Cascada Vânturătoarea), ostali se smeštaju, I ko želi može da ode na kupanje u nekom od toplih lekovitih izvorišta u banji. Noćenje.\r\nVodopad Vanturatoarea je jedan od najatraktivnijih I najviših u južnim Karpatima, koji sa 45 metara visine predstavlja najviši vodopad u slobodnom padu u Rumuniji. Vodopad se nalazi na rečici Ogašul Slačini (Ogaşul Slacini).', 1, '', '2021-02-27', 3),
(23, 'Severni Kučaj, Turija stenje (238 m), vodopad Šumeće, Vrelo Rakova Bara', 'Rakobarski vis se nalazi u ataru sela Rakova bara, na 130 km od Beograda (2 sata vožnje). Put vodi preko Požarevca i Turije, gde se skreće za Rakovu baru. Nekih 5-6 km pre Rakove bare, nalazi se čudotovorni manastir Tumane, koji svakako treba posetiti.\r\nU selu Rakova bara, prati se glavni, asfaltni put, do ovog mesta.Tu se parkirajte i nastavite u pravcu zelene kuće. Posle zelene kuće, skrenite levo i uzbrdo, na makadamski put.Odavde samo pratite glavni seoski put. Odmah se ukazuje Rakobarski vis.Oko 1,5 do 2 km od početka staze, dolazi se do vodopada Malo vrelo. Vodopad je veoma lep. Visok je 15 m. Zaobiđite ga s desne strane, kako biste ga celog sagledali i uživali u prizoru.Od vodopada kreće uspon na Rakobarski vis (691 m). Od ovog mesta, vrh je udaljen 4-5 km. Prelazi se preko livade, iznad vodopada, i prolazi pored prikolice prikazane na slici.Dalje se samo prati makadamski put, koji ide uzbrdo. Usput je lep pogled na okolne vrhove.', 1, '', '2021-03-02', 5),
(24, 'Via ferrata \"Gornjak\"', 'Misterije istočne Srbije se najbolje upoznaju u direktnom kontaktu sa njom. Popnite se na vrhove Malog i Velikog Vukana, odakle se pruža pogled na dolinu reke Mlave, stari karavanski put i ostatke grada Vukana.Vodimo vas na novu ferratu u Gornjačkoj klisuri.Ovo je idealna tura za one koji se pripremaju za odlazak u Dolomite. Nakon toga, relaksirajte se u termalnim izvorima banje Ždrelo i uživajte u homoljskim specijalitetima.\r\n\r\nPre polaska u našu avanturu, kratko objašnjenje šta je to via ferata:\r\n\r\nVia ferata u prevodu znači – gvozdeni put. To je put kroz često nedostupan teren, koji je otvoren postavljanjem metalnih prečki ili “gazišta” i zaštićen čeličnim užetom (sajlom). Suština moderne ferate je čelična sajla koja ide duž trase i periodično je fiksirana za stenu. Sajla služi za osiguravanje, ali se u pojedinim deonicama može koristiti kao pomoćni ručni držač.Ono što je sigurno za ovu avanturu je da će doživljaj biti jedinstven i da ćete biti u mogućnosti da osetite kako to izgleda biti na litici okružen prazninom oko sebe, a opet apsolutno bezbedni.', 2, '', '2021-04-03', 3),
(25, 'Crnokosa (Šarampov 809 m.)', '07:30 Polazak od lokomotive (doći 15 min. pre polaska). Prevoz Čačak - Kosjerić. Dolazak do motela Park u Kosjeriću oko 8:30. Pauza za doručak i kafu. U blizini motela postoje prodavnica i pekara. Oko 09:00 polazak na pešačku turu, od motela Park (motel je u vrhu varošice, na 420mnv) uz Filipovića potok do vrha Šarampov (oko 809mnv). Nakon kraćeg zadržavanja na vrhu sledi blag spust Graničkim brdom\r\n\r\n– grebenom koji je granica između opština Kosjerić, Užicei Požega. Ide se ka Zaselju i Kalenićima (350mnv).\r\nSilazak u selo Kalenići oko 15h.\r\nDužina staze je oko 15km, staza nije tehnički zahtevna.\r\nNakon pauze, oko 16:00 polazak za Čačak, dolazak do 17:00 časova.\r\n\r\nNAPOMENE :\r\n• Prijave: najkasnije do 27.01.2015.godine, na sastanku ili na telefon 060 39 20 140, uz obaveznu akontaciju od 400 din. Cena prevoza biće oko 500-600 din. u varijanti popunjenog vozila. Konačna cena zavisiće od broja učesnika. U slučaju odustajanja potrebno je naći zamenu, u protivnom akontacija se ne vraća.\r\n• Ishrana: Sve vreme u sopstvenoj režiji.\r\n• Dokumenta: Lična karta, zdravstvena knjižica, planinarska knjižica.\r\n• Oprema: Lični pribor, planinarska oprema prilagođena zimskim uslovima (zaštita od snega, vetra, hladnoće...), rezervna odeća i obuća....\r\n• Ostalo: Predloženi plan i satnica su okvirni. U slučaju potrebe organizator zadržava pravo izmene plana akcije.\r\n•Svi učesnici na akciju polaze dobrovoljno, na sopstvenu odgovornost, u skladu sa Pravilnikom o bezbednosti PSS i svojim zdravstvenim i fizičkim sposobnostima, i uz poštovanje navedenog plana. Takođe, obaveza učesnika je da se pridržavaju Protokola o ponašanju na akcijama PD ,,Kablar\".', 1, '', '2021-03-03', 1),
(26, 'Iran, Alvand 3571 m, pustinja Kalut Shahdad', 'Pustinja Lut, u široj zoni Dašt-e Lut, velika je pustinja soli koja se nalazi u provincijama Kerman i Sistan kao i Balučistan, u Iranu. To je 25-ta po veličini pustinja na svetu i uvrštena je na UNESKO-ovu listu svetske baštine 17. jula 2016.[1] Površina njenog peska merena je na temperaturama od 70 ° C (159 ° F),[2][3] što je čini jednim od najsušnijih i najtoplijih mesta na svetu.\r\n\r\nIran je klimatski deo afro-azijskog pojasa pustinja, koji se proteže od Zelenortskih Ostrva do zapadne Afrike, sve do Mongolije. Pačasta, izdužena, svetla boja u prvom planu (paralelno sa planinskim lancem) je najsevernije od sušnih jezera Dašta, koja se protežu na jugu 300 kilometara (190 milja). U skoro tropskim pustinjama povišena područja uzimaju većinu padavina. Kao rezultat toga, pustinja je u velikoj meri abiotska zona.\r\n\r\nGeografija Irana sastoji se od visoravni okružene planinama i podeljene na drenažne bazene. Dašte Lut je jedan od najvećih pustinjskih bazena, dugačak 480 kilometara i širine 320 kilometara ,a smatra se jednim od najsušnijih mesta na Zemlji.\r\n\r\nPovršina pustinje je oko 51.800 kvadratnih kilometara (20.000 kvadratnih milja). Drugi veliki sliv je Dašte Kavir. Tokom prolećne vlažne sezone voda se kratko spušta sa Kermanskih planina, ali ubrzo presuši, ostavljajući iza sebe samo kamenje, pesak i so. Istočni deo Dašte Luta je niska visoravan prekrivena slanim površinama. Suprotno tome, centar je vetar isklesao u niz paralelnih grebena i brazdi, koji se prostiraju na preko 150 km (93 milje) i dostižu 75 metara visine. Ovo područje je takođe prepuno jama i pećina. Jugoistok čini velika pečana masa, poput saharskog erga, sa dinama visokim 300 metara,koje su među najvišim na svetu. ', 3, '', '2021-03-06', 5),
(27, 'Via ferrate \"White Wolf\", Rumunija', 'Mala klisura pored mesta Baia de Fier u Rumuniji je pravi raj za ferataše. Dvanaest ferata težine od B do E će biti po ukusu svih ljubitelja stene. Pristup na 5 minuta od parkinga, silazak na 10 minuta šumskom stazicom, smeštaj na 10 minuta hoda od prvih ferata, male pećine, viseći mostovi, atraktivne staze i ferate će vam učiniti ovu akciju nezaboravnom! U zavisnosti od sastava grupe popećemo barem 6 via ferrata, a koje ćemo penjati ćemo se\r\ndogovoriti po formiranju grupe. Via ferrate Creasta Pesterii (Greben pećine), Marea Crapatura (Velika pukotina), Loreley  su težine B i svako ih može popeti. Pantera Roz (Pink Panter) i Saritoarea Ursului (Skok medveda) su težine C, dve Spirale – srednja i velika (Spirala Medie, Spirala Mare), Vanturilor, kao i Amfiteatar zmaja\r\n(Amfiteatrul Zmeilor) su prava poslastica – kombinacija horizontalnih i vertikalnih ferata težine D, dok je Laura za one najizdržljivije sa ocenom E. Postoji mogućnost obilaska jedne od najlepših pećina u Rumuniji  Pestera Muierilor\r\nPLAN AKCIJE\r\nPetak 03.07. Polazak na akciju iz Beograda, u 15h. Vožnja đerdapskom magistralom do mesta Baia de Fier sa usputnim pauzama. Dolazak u mesto u kasnim večernjim satima i smeštaj u višekrevetnim sobama. Noćenje. \r\nSubota 04.07. penjanje ferata do kasnih večernjih časova i opciono  - obilazak pećine Muierilor. Noćenje. \r\nNedelja 05.07.napuštanje smeštaja, penjanje dogovorenih ferata i polazak za Beograd oko 14 h. Usputni obilazak „Šarene šume“. Vožnja đerdapskom magistralom sa usputnim pauzama kod Golubačke tvrđave i Kazana. Dolazak u Beograd u večernjim časovima.\r\n\r\nISHRANA – u sopstvenoj režiji (tkzv – iz ranca). Postoji mogućnost poručivanja hrane u smeštaju\r\n\r\nDOKUMENTA – planinarska knjižica sa plaćenom članarinom za 2020.god, pasoš, putno zdravstveno osiguranje\r\n\r\nOPREMA – obavezna via ferata oprema (šlem, ferata set, pojas obezbeđeni od strane organizatora) kao i rukavice i naočare za sunce. Odeća i obuća mora biti prilagodjena vremenskim uslovima za prolećne uspone.', 2, '', '2021-04-13', 3),
(28, 'Ozren i Devica - Leskovik (1174 m),  Oštra čuka (1075 m), vodopad Ripaljka', 'Planina Ozren se nalazi u jugoistočnoj Srbiji i predstavlja poslednju antiklinalu i balkansku planinu na severozapadu. Planina Ozren je sastavljena od krečnjaka različite starosti (trijas, jura i kreda). Planina se pruža pravcem od severozapada ka jugoistoku u dužini od 15 km i odvaja sokobanjsku kotlinu od aleksinačke. Najviši vrh Ozrena je Leskovik (1174 mnv). Vrh se nalazi na jugozapadnom delu planine. Planina je uglavnom blagih kontura osim na jugozapadu gde se nalazi strmi krečnjački odseci. Na planini postoji veliki broj vrtača ali ne u tolikoj meri kao na Devici. Na Ozrenu uglavnom dominira bukova šuma (severoistočna strana). Granica Ozrena i Device predstavlja krečnjački rased gde se nalaze brojna sokobanjska izletišta \"Ozrenske livade\". Na mestu raseda se javlja i tok reke Gradašnice koja formira nekoliko vodopada i slapova. Najveći od njih je vodopad \"Ripaljka\" sa visinom od 17 metara. Devica i Ozren su najbiliži kod mesta Vlasina (oko 1000 mnv) koja predstavlja krašku visoravan. Visoravan Vlasina se nalazi 11 km od Sokobanje. Vlasina je glavno planinarsko polazište za vrhove: Leskovik i Oštra Čuka. Vrh Leskovik je od Vlasine udaljen oko 6 km. To je prva staza koju je naše društvo markiralo, još 2010. godine. ', 2, '', '2021-04-11', 4),
(29, 'Kanjon reke Nera i Beušnice', 'Reka Nera predstavlja granicu između Srbije i Rumunije. Od njenog ušća u Dunav počinje Đerdapska klisura, a u susednoj Rumuniji njene predele krase veoma slikoviti i interesantni pejzaži koji su pod zaštitom države.\r\n\r\nNacionalni park, kanjon Nere i Beušnice (Cheile Nerei-Beușnița) pripada jugozapadnom delu Rumunije. Udaljen je 25 km od granice sa Srbijom i nalazi se u Banatskim planinama. Do kanjona se dolazi preko Bele Crkve i graničnog prelaza Kaluđerovo. Ovo zaštićeno područje zauzima preko 36.000 hektara, a reka Beu, Nerina pritoka je pravi biser nacionalnog parka.\r\n\r\nKamp je jedino mesto u Nacionalnom parku gde možete kupiti neko osveženje ili poručiti porciju pastrmke.\r\nCena sokova je 5 Lei, kafa 3 Lei, a porcija pastrmke 17 Lei.\r\n\r\nVelika mana parka jeste to što nigde, pa čak ni u kampu ne postoji toalet, pa se sve obavlja u potpuno prirodnom okruženju.\r\n\r\nPut vodi do vrela koje se zove Begovo oko (Ochiu Bei). Ovo jezerce je dugačko oko 15 metara i do njega vodi mostić ispod kojeg se nalaze slapovi gde se može natočiti voda za piće. Nama je delovalo da mu je dubina oko 2 metra, jer prozirnom vodom stvara iluziju manje dubine. Međutim, do dna Begovog oka ima oko 10 metara. Mene je po boji i mirnoj vodi podsetilo na naše Krupajsko vrelo.', 1, '', '2021-03-17', 2),
(30, 'Kanjon reke Gradac, Strmna gora (505 m)', 'eka Gradac je udaljena od Valjeva nekih 5km, a od Beograda do Valjeva, ako se putuje Ibarskom magistralom, ima 100km. Ovde imate priliku da vidite manastir Ćelije, zadužbinu kralja Dragutina Nemanjića, iz 13. veka. Takođe, ovaj manastir je bio dom čuvenom duhovniku, mudracu i iscelitelju, Avi Justinu Popoviću, kome veliki broj namernika i danas dolazi da poseti mošti. S druge strane, ništa manje nije vredan manastir Lelić, a takođe je neizbežan tokom šetnje. Nalazi se na nekom 11~tom kilometru od Valjeva, u istoimenom selu. Zadužbina je čuvenog duhovnika, vladike Nikolaja Velimirovića. To je prelepa\r\n\r\n\r\n\r\nKanjon reke Gradac je impozantno remek~delo prirode, što dokazuje sama okolina. Ovde postoji preko sedamdeset pećina za koje se pouzdano zna, što je zaista neverovatno za ovako malu reku. A time se ne mogu podičiti ni mnogo veće reke. S toga ćete imati priliku da vidite Degurićku pećinu, koja prednjači u odnosu na druge dužinom svojih hodnika, veličinom, a posebno lepotom pećinskog nakita. U blizini pećine je istoimeno selo, a nadomak sela je brana koja pored svoje svrhe, predstavlja i omiljeno kupalište Valjevaca.\r\nSmatra se da je ovo područje bilo dom čoveku još od pradavnih vremena, a tragovi koji su ovde pronađeni vode nas čak do paleolita. Pored toga, bilo je stanovništva i u antičkom dobu, kao i u srednjem veku, a otkriveno je mnoštvo kelija~isposnica. crkva sagrađena u moravskom stilu, kombinovanjem kamena, cigle i sige, što posebno doprinosi njenom šarmu.\r\nGradac je sam po sebi veoma specifična reka, jer se od svog izvorišta i preko svog toka različito ponaša. Izvire podno planine Povlen, najveće u nizu valjevskih planina, da bi nakon nekoliko kilometara ponirala i ponovo izbijala na površinu. Nastaje na mestu gde se sastavljaju Bukovska reka i Zabava i odatle, pa sve do ušća u reku Kolubaru, teče kroz klisurasti krajolik u dužini od 28km. Sam kanjon Gradca, koji je usecan kroz vekove, dug je 22.7km i predstavlja pravu avanturu. Posebno su interesantna vrela ove reke koja se nižu čitavim njenim tokom.', 2, '', '2021-03-15', 2),
(31, 'Boranja (Šarena bukva 770 m)', 'Od mesta Stolice na putu Loznica-Krupanj, sa prevoja, ova staza desno vodi uzbrdo makadamskim  putem  prema zaseoku Gajići. Ovaj zaseok nakon 3 km pešačenja obilazimo sa desne strane pečicom koja predstavlja širu šumsku stazu. Ponovnim uklapanjem na makadamski put, teren je nešto ravniji i kroz Gustu bukovu šumu se stiže do planinarskog doma ,,Šarena Bukva,, . Ovo je odlična lokacija za prelazak na planinu Jagodnju i obilazak  Mačkovog Kamena, kao i Radaqskog jezera i istoimene banje.', 1, '', '2021-03-20', 1),
(32, 'Iverak, Debeli rt (426 m)', 'Iverak se nalazi na teritoriji grada Loznice, u neposrednoj blizini planine Cer, tako da ima mišljenja da je Iverak ogranak Cera.\r\n\r\n\r\nSa najvišim vrhom Debeli rt sa 426 metara nadmorske visine, Iverak spada u red niskih planina. Vrlo je bogat potocima (Ribarički, Klokočevac, Gradiština, Osoje, Panića potok, Jezerin, Zelenika), dok je površina prekrivena raznovrsnim drvećem (bukva, hrast, cer, bagrem, gram, crni bor, lipa, beli bor, smrča, ariš, javor, crni grab).\r\n\r\nNa planini postoje ostaci manastira kojeg je podizao jeromonah Georgije Bojić-Džidža, rodom iz Jaska. Grupa meštana pokrenuli su inicijativu da se obnovi manastir, očistili prostor i postavili spomen ploču. Spomenik u obliku krsta je postavljen i na izvoru ispod same ruševine. ', 2, '', '2021-03-21', 3),
(33, 'Cer - Jagodnja - Lipove Vode - Krupanj', 'Jagodnja (ćiril. Јагодња) je mala i niska planina u zapadnoj Srbiji, iz grupe Podrinjskih planina. Njezin glavni greben pruža se dinarskim pravcem sjeverozapad - jugoistok, jugozapadno od Krupnja, između rijeke Uzovnice na istoku, rijeke Drine (Zvorničkog jezera) na zapadu i jugu, te Boranjske reke na sjeveru. To je manji razvijeni masiv s valovitim glavnim grebenom u njezinom sjeveroistočnom dijelu s koga se uzdižu i najviši vrhovi: Košutnja stopa (940 m), Mačkov kamen (923 m) i Perunika (918 m.). Dvije grupe sekundarnih grebena, razdvojenih rijekom Velikom, odvajaju se od glavnog grebena Jagodnje i pružaju se u smjeru doline Drine - jedna razvedenija prema jugozapadu (okomito na dinarski smjer) i druga (tu se zapravo radi o tri kraća manja grebena) prema jugu. \r\n\r\nNjezinu temeljnu građu čine permokarbonski škriljevci, a u krovini (povlati; stijena koja se nalazi neposredno iznad istraživanoga ili iskorištavanoga sloja nekoga rudnog ležišta) trijaski pješčenjaci i vapnenci, s žicama eruptivnih stijena. Od širokog planinskog tjemena stupnjevito se spušta prema Drini i Jadru niz zaravni, a s tjemena se dižu manja uzvišenja (Mačkov kamen 923 m, Lipnička glava 773 m). Šuma je razrijeđena prostranim krčevinama oko planinskih sela. Kod Mačkovog kamena se račvaju putevi ka Košutnjoj stopi, Krupnju i selu Uzovnici pored Drine, na magistralnoj cesti.\r\n\r\nJagodnja i Boranja predstavljaju jedinstvenu cjelinu, posebno njihov najviši greben, i malo tko može reći gdje zapravo prestaje jedna i počinje druga planina. Jedna se nadovezuje na drugu i prožima. Obje u poznate po rudarskoj aktivnosti koja počinje još u rimsko doba, pa preko srednjeg vijeka do novijih dana.', 1, '', '2021-03-23', 2),
(34, 'Durmitor, zimski bivak u Velikoj kalici, - kuloari; Kuline, Bezimenog vrha, Miloševg toka, Šljemena', 'Durmitor je najlepša crnogorska planina gde je tektonskim delovanjem i erozijom, rečnom i ledenjačkom, stvoren planinski svet fantastičnih oblika, kojeg je dobar pešak sposoban u podnožju obići za jedan dan. Uz vrhove su njihovi verni pratitelji – ledenjačke doline, te pregršt planinskih jezera, ovde poznatim kao „gorske oči“. Oštri vrhovi i grebeni čine ga idealnim mestom za planinarenje zimi i leti. Kružni put oko njegovog ruba dugačsk je svega 90 km. U tako relativno malom području masiv Durmitora, ima čak 48 vrhova iznad 2000m, od čega 40 preko 2100m, 27 preko 2200 m, 18 preko 2300 m, 7 preko 2400m i samo jedan preko 2500 m (Bobotov kuk); Na istom tom području ima 17 jezera iznad 1400 m, od čega 11 iznad 1500 m, 9 iznad 1600 m, 4 iznad 1700 m, dva iznad 2000m (Zeleni vir i Miloševa lokva), a najdublje je Crno jezero (49 m). Na istom tom području ima 27 markiranih i 12 nemarkiranih staza. Markiranih staza ima preko 2000 km a prolaze kroz sve delove Durmitora i otkrivaju sve lepote ovog nacionalnog parka. Posebnost Durmitora je u lepoti raskošnih planinskih pejzaža, u osvajanju visina od kojih zastaje dah i s čijih vrhova se pružaju fantastični pogledi na udaljene horizonte kanjona Pive i Tare, te najviših planina Albanije, Srbije i Bosne (Prokletije, Kopaonik i Zelengora).\r\n\r\nPodvlačino da Durmitor ima 48 vrhova preko 2000 metara, 18 gorskih očiju predivnih glečerskih jezera, 5 kanjona i preko 500 km markiranih staza i spada u jednu od najbolje markiranih planina.\r\n\r\nIstovremeno Durmitor pruža idealne uslove za „osvajanje“ i planinarenje. Na realtivno malom prostoru, postoji planinski svet fantastičnih oblika. Odlikuje se oštrim vrhovima, neki nalik na alpske igle (Minin bogaz, Zupci, Sohe) i oni drugi, sa masivnim kupolama i/ili strana šarom iseckana nalik na prutove (Prutaš, Šareni pasovi), pojedini su vrhovi vertikalno zasečeni (Savin kuk , Šljeme) jedinstvenog izgleda i boje (Međed), jarko obojeni (Crvena Greda) ili oni treći sedleni (Sedlen greda), uvijeni ( Uvita greda), obli (Obla glava), usamljeni ( Stožina) i dr. Zastrašujući, tamni, svetli, minijaturni, gorostasni i svi oni su pravi raj za planinare. U nastavku su nabrojane odabrane planinarske ture sa dobro markiranim rutama ka nekoliko najviših vrhova Durmitora.', 1, '', '2021-03-25', 5),
(35, 'Medvednik (Veliki Medvednik 1274  m)', 'Do vrha Medvednika može se doći na nekoliko načina. Na vrh se može popeti iz sela Drenajić, što je najduža varijanta, kao i preko planine Jablanik. Ovde ću opisati stazu koja vodi od planinarskog doma “Krušik” (850 m). Inače, kažu da je Medvednik dobio takvo ime jer, kada se gleda iz daljine, liči na medveda koji spava?!\r\n\r\nDakle, Ibarskom magistralom ide se do Valjeva (oko 100 km) i onda još 30 km, ka prevoju Debelo Brdo. Prati se putokaz za Bajinu Baštu. Na putu ka prevoju, prolazi se pored brane Rovni i kroz selo Poćutu. Na Debelom Brdu, sa desne strane se vidi skretanje, koje vodi ka domu. Put je makadamski i, uz pažljivu vožnju, može se doći do samog doma. Od doma, ka vrhu, vode markirane staze. Staza je uglavnom makadamska i nema mnogo eksponiranih mesta. Do vrha se stiže preko Kedine vode, izvora na kome se možete osvežiti čistom, planinskom vodom.\r\nDalje se prate marakcije, sve dok se ne dođe do jedinog eksponiranog mesta, sa koga se vidi susedna planina, Bobija.', 2, '', '2021-03-30', 4),
(36, 'Beljaničko pobrđe, Venac (509 m), Ribarska klisura', 'Млава представља главни речни ток, хидрографску артерију Хомоља. Настаје од снажног Жагубичког врела, а неких 150 m низводније прима реку Тисницу која у летњим месецима пресушује. Ток Млаве се може поделити у три сливна подручја: горњи - Хомоље, средњи - Млава и доњи - Стиг.\r\n\r\nМлава најпре тече кроз Жагубичку котлину у дужини од 11,5 km. Код насеља Изварица, напушта равну котлину, и улази и епигенетску Рибарску клисуру. Кроз Рибарску клисуру тече у дужини од 9,5 km. Затим, када изађе из Рибарске клисуре тече неких 7 km кроз Крепољинско-крупајску котлину, да би потом ушла у Горњачку клисуру и кроз њу текла неких 16 km и изласком из ње напустила подручје Хомоља. У Рибарској клисуру Млава је усекла три меандра, а у Горњачкој четири. Укупна дужина Млаве кроз Хомоље износи 44 km, а до ушћа у Дунав дужина реке је 158 km. Вредности протицаја на Млави су различити и на њих утичу атмосферске падавине и отапање снега на оближњим планинама. Највећи протицај Млава има у априлу, а најмањи у септембру. Млава има зеленкасту боју на коју највише утиче зеленило које се налази уз саму реку и флора која се у њој налази. У реци се могу наћи различите врсте рибе од којих је најпознатија \"Млавска\" пастрмка. Поред пастрмке доста је заступљен скобаљ, клен и кркуша. Река Млава је у свом току кроз Хомоље донекле задржала карактеристике чисте планинске реке, али вода ипак није за пиће јер је све више отпада које становништво неконтролисано баца у реку, што је за сваку осуду и томе се што пре мора стати у крај. Надлежне институције се овим проблемом морају више позабавити јер не смемо дозволити уништавање и загађивање највећег блага које у Хомољу имамо. Млава као туристички мотив и објекат има велике вредности и функције. Привредне функције су водопривреда и хидроенергија, а атрактивне и рекреативне функције које има су врела, клисуре, рибњаци, спортски риболов и рекреативни амбијент. На појединим секторима долине рекреативне вредности реке појачавају питоми пејизажи приобаља који су погодни за излете (пикнике) и спортске активности. Најлепши деолови тока Млаве кроз Хомоље представљају клисуре и меандри које је у њима усекла. Прави куриозитет представља део Рибарске клисуре, где је брза и хучна Млава направила меандар скоро кружног облика. У том меандру међу литицама смештемо је идилично село Рибаре, најлепши кутак за сеоски туризам.', 2, '', '2021-04-16', 3),
(37, 'Rajac - Suvobor', 'Rajac je naša poznata planina koja iako spada u niske (847 m) ipak pruža dosta veoma interesantnih sadržaja. Dovoljno je blizu Beograda tako da za jedan dan može veoma brzo da se ode tamo i da se vrati natrag bez nekog većeg zamaranja u putovanju. Ukoliko se želi duži ostanak tamo, smeštajnih kapaciteta ima dosta, počevši od planinarskog doma “Čika Duško Jovanović” koje je u vlasništvu PD “Pobeda”, preko PTT doma, kafane “Lovačka priča” a takođe i u privatnim kućama. Po celom Rajcu postoji niz dobro markiranih planinarskih staza, od kojih se neke nastavljaju mnogo dalje sve do Ravne gore i Divčibara u pravcu zapada i do Ovčara i Kablara prema jugu!\r\nOvaj lagani krug počinje kao i većina ostalih staza kod planinarskog doma gde je najbolje ostaviti kola zbog velikog parkinga ispred. Prvo se ide standardno uzbrdo asfaltom koji vodi prema Takovu i odmah nakon par stotina metara postoji česma gde se može obskrbiti vodom. Nastavlja se dalje sve do kafane “Lovačka priča” i tu se skrene desno putem koji vodi prema vrhu Rajca. Ide se još 400 m uzbrdo sve dokle postoji novoizgrađeni asfalt pa se onda skrene levo na makadam. Dalje se ide u pravcu juga, a vrh Rajca ostaje sa desne strane.', 2, '', '2021-04-17', 1),
(38, 'Via ferrata \"Sokolov put\", BiH', 'Na području Crvenih stijena na Romaniji  22.11.2020. godine svečano je predstavljen novi turistički sadržaj Sarajevsko-romanijske regije – Via ferata “Sokolov put“ kao dio projekta Enjoy Sarajevo-Romanija Region koji finansiraju Evropska unija i Savezna Republika Njemačka.\r\n\r\nVia ferata, odnosno staza po stijenama uređena čeličnim pomagalima, namijenjena je svima, pogotovo onima bez prethodnog alpinističkog iskustva.\r\n\r\nDužina ferate iznosi 350 metara i sa dva viseća mosta predstavlja jedinstvenu atrakciju u BiH.\r\n\r\nGradonačelnik Istočnog Sarajeva Nenad Vuković rekao je da su danas otvorili feratu na Crvenim stijenama kao novi adrenalinski i atraktivan turistički sadržaj, te da očekuje veliki broj dolazaka i posjeta na ovu lokaciji u narednom periodu, jer je sadržaj vrijedan pažnje.\r\n\r\nOn je dodao da je na području Romanije predviđeno uređivanje pješačkih staza koje će u dužini od 45 kilometara povezati lokacije Crvene stijene, pećinu Starine Novaka i planinarski dom “Stajna”.\r\n\r\nDirektor Gradske razvojen agencije Istočno Sarajevo – RAIS Mladenka Pandurević istakla je da je ovo  jedna od niza aktivnosti u okviru projekta koji se implementira na području tri opštine grada Istočno Sarajevo. Pored svih outdoor turističkih sadržaja projekat je značajan i za mikro mala i srednja preduzeća koja će biti uključena u implemetaciju projekta i kojima će biti pružena podrška putem obuka i promocije njihove ponude.', 2, '', '2021-04-21', 1);
INSERT INTO `travels` (`id`, `heading`, `body`, `difficulty`, `travel_image`, `date`, `guide_id`) VALUES
(39, 'Nacionalni park Đerdap vidikovac Sokolovac (626 m)', 'Trek polazi ispred tunela broj 17 na Đerdapskoj magistrali odmah na kraju mosta na reci Pesača te ako dolazite redovnom autobudkom linijom, posle sela Dobra, treba na vreme reći vozaču gde treba da vam stane.\r\n Polazi se solidnim kolskim putem.\r\n\r\n U početku staza se nešto odvaja od reke Pesača ( potok), ali se kasnije postepeno približava Pesači i u dva navrata menja stanu potoka.  (Posleobilnih kiša  septembra 2014 god bujice su odnele put u kanjonu Pesače te je kretanje tim delom sada otežano.) \r\nVeoma je važno zapaziti mesto gde trek napušta ovaj kolsi put i prelazi na suprotu (levu) stranu potoka i tu počinje uspon na Skokolovac. (\r\nOvo mesto je doduše obeleženo tablom nacinolnog parka Đerdap ali je veoma zaraslo u gustišu te stoga savetujem da se na vreme pogleda GPS. Po prelasku Peače treba odmah pronaći kolski put koji je sada nesto strmiji. Posle par stotina metara put izlazi iz bukove šume i postaje praktično nevidljiv (prohodan) od visoke trave.To je trenutak kada poonovo treba skrenuti desno i slobodno preko polja ići do obližnjeg salaša. U blizini kuće postoji izvor vode sumnjivog kvaliteta. U svakom slučaju preporučujem da se na tom mestu napravi kraća pauza.\r\n', 1, '', '2021-04-24', 2);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `guides`
--
ALTER TABLE `guides`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `travels`
--
ALTER TABLE `travels`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `guides`
--
ALTER TABLE `guides`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `travels`
--
ALTER TABLE `travels`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
